version: "3.8"

services:
#runs mongo image
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
# runs Node.js API
  web:
    build: .
    container_name: employee-app
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - NODE_LOCAL_PORT=8082
    restart: unless-stopped
# runs React frontend
  frontend:
    build: ./client
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - web
    restart: unless-stopped
# holds database data
volumes:
  mongo_data: